Mention build command on Workflow page
ionic-team/capacitor-docs pull request #127
Opened 2022-12-16 21:43 UTC by dotNetkow

never say never!

2023-11-08 18:39 UTC, giralte-ionic approved these changes

2023-11-09 17:12 UTC, IT-MikeS requested changes

2023-11-09 17:12 UTC, IT-MikeS commented on docs/main/basics/workflow.md
> +After `sync`, you are encouraged to open your target platform's IDE: Xcode for iOS or Android Studio for Android, for compiling your native app. Alternatively, use the [cap build command](../../cli/c
instead of `../../cli/commands/build` use web path `/docs/cli/commands/build`

2024-07-01 18:21 UTC, jcesarmobile approved these changes

2024-07-01 18:21 UTC, merged