docs: Xcode 14 is required for Capacitor 5
ionic-team/capacitor-docs pull request #156
Opened 2023-03-08 18:57 UTC by theproducer

2023-03-08 19:33 UTC, giralte-ionic approved these changes

2023-03-08 19:54 UTC, markemer approved these changes

2023-03-08 21:54 UTC, jcesarmobile requested changes
Xcode 13 is also mentioned here
https://github.com/ionic-team/capacitor-docs/blob/main/docs/main/ios/index.md

2023-03-09 16:52 UTC, jcesarmobile approved these changes

2023-03-09 16:55 UTC, merged