docs: Setting v5 docs to current
ionic-team/capacitor-docs pull request #176
Opened 2023-05-03 22:24 UTC by theproducer

2023-05-03 22:25 UTC, ItsChaceD requested changes

2023-05-03 22:25 UTC, ItsChaceD commented on docs/main/updating/5-0.md
>  Install the `next` version of the Capacitor CLI to your project:
Should say `latest` instead of `next`

2023-05-03 22:34 UTC, IT-MikeS commented
Other than Chance's comment lgtm

2023-05-03 22:34 UTC, IT-MikeS approved these changes

2023-05-04 00:07 UTC, IT-MikeS approved these changes

2023-05-04 00:10 UTC, merged